spring.application.name=prueba-tecnica
spring.datasource.url=jdbc:postgresql://localhost:5432/prueba_tecnica
spring.datasource.username=postgres
spring.datasource.password=TU_PASSWORD

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true